### ISSUE TITLE
Request id for TinyAPRS

### ISSUE THREAD

**Issue by shawnchain** [hessu/aprs-deviceid#14]
- tocall: APTAxx where xx will be the revision numbers
- vendor: BG5HHP(shawn.chain@gmail.com)
- model: TNC/Tracker/Digi
- OS: No OS
- Features: An ATMEGA328p based with KISS TNC/Tracker/Digi features.

for MIC-E, I would like to use 'TA'.

The project TinyAPRS:  http://github.com/shawnchain/aprs/

Thanks,

Shawn.

**Comment by hessu** [comment]
Hi,

Please read through the instructions in https://github.com/hessu/aprs-deviceid first, and more specifically, please get in touch with Bob first to have it in his tocalls.txt index which is currently the primary source. APTIXX seems to be taken already unfortunately. Also, 'TI' won't work for mic-e due to technical reasons, Bob can assign you something else.

**Comment by shawnchain** [comment]
Hi,
Update: WB4APR has assigned the APTAxx for TinyAPRS.
Thanks,

Shawn

**Comment by PhirePhly** [comment]
Just an observation, but APTA* was already taken. Bob assigned you a TNCID that was already assigned to K4ATM's tiny track. I don't know how we want to handle this in this database.

tocalls.txt:

      APTAxx  K4ATM's tiny track
      APTAxx  TinyAPRS by BG5HHP

**Comment by shawnchain** [comment]
Just confirmed with Bob(WB4APR) that new id APTBxx will be assigned to device "TinyAPRS by BG5HHP"

**Comment by shawnchain** [comment]
tocall: APTBxx where xx will be the revision numbers
vendor: BG5HHP(shawn.chain@gmail.com)
model: TinyAPRS TNC
OS: No OS
Features: An ATMEGA328p based with KISS TNC/Tracker/Digi features.

**Comment by hessu** [comment]
Thanks for the ticket, and sorry for the slow reply. Added APTB??.

**Comment by shawnchain** [comment]
Thank you for the update.
