### ISSUE TITLE
New device APATAR

### ISSUE THREAD

**Issue by barisdinc** [hessu/aprs-deviceid#57]
Could you please add the following debve (it is already in Bob’s file)

tocall: apatar
vendor: TA7W/OH2UDS Baris Dinc
model:  ATA-R APRS Digipeater by TA7W/OH2UDS and TA6AEU 
class: digipeater

Thanks
baris OH2UDS

**Comment by barisdinc** [comment]
I will be happy if you can change the class to digipeater, thanks.

**Comment by hessu** [comment]
Ok, thanks for the note, adding it now. I hope there are no collisions, as previously there was an APATxx allocation for AnyTone, a Chinese manufacturer which has not been great with allocating identifiers. I've made it like this so that the vendor information does not mix up in the model field:

 - tocall: APATAR
   vendor: TA7W/OH2UDS Baris Dinc and TA6AEU
   model: ATA-R APRS Digipeater
   class: digipeater

**Comment by barisdinc** [comment]
Hi,
As you mentioned we are having issues with Anytone, our device is being reported as "Anytone" on aprs.fi details page. 
https://aprs.fi/info/a/TA7W-2
How can we fix this issue? Can it be a solution to move it up before "tocall: APAT??" 

Thanks

**Comment by hessu** [comment]
Hi,

The longest match is searched for, order in file does not matter. It'll get updated when aprs.fi fetches a new copy of this database.

73!
